export { Icon, type IconName } from "./Icon"
export { Eyebrow } from "./Eyebrow"
export { Logo } from "./Logo"
export { Button, type ButtonProps } from "./Button"
export { Input, type InputProps } from "./Input"
export { Select, type SelectProps } from "./Select"
export { Checkbox, type CheckboxProps } from "./Checkbox"
export { Switch, type SwitchProps } from "./Switch"
export { Badge, type BadgeTone } from "./Badge"
export { Card } from "./Card"
export { Avatar } from "./Avatar"
export { RiskBadge, type RiskLevel } from "./RiskBadge"
export { StatusChip, statusFamily, type CaseStatus } from "./StatusChip"
export { CaseCard } from "./CaseCard"
export { Timeline, type TimelineItem } from "./Timeline"
export { AIMessage, UserMessage } from "./ChatMessage"
export { AppShell, type NavItem } from "./AppShell"
export { TopBar } from "./TopBar"
export { SearchInput, type SearchInputProps } from "./SearchInput"
export { StarRating, RatingDisplay } from "./StarRating"
export { DocumentViewer } from "./DocumentViewer"
export type { DocumentViewerProps } from "./DocumentViewer"
export { ImageCarousel } from "./ImageCarousel"
export type { ImageCarouselProps, CarouselImage } from "./ImageCarousel"
export { PendingActionsWidget } from "./PendingActionsWidget"
export { SpecialistChips, type SpecialistChipsProps, type Specialist } from "./SpecialistChips"
export { SpecialistBadge } from "./SpecialistBadge"
export { useSpeechRecognition, appendTranscript } from "./useSpeechRecognition"

// ── Componentes de estado de erro ─────────────────────────────
export { ClientBackButton } from "./ClientBackButton"
export { SessionExpiredModal } from "./SessionExpiredModal"
export { ForbiddenBlock } from "./ForbiddenBlock"
export { UploadErrorModal, type UploadFile } from "./UploadErrorModal"
export { LLMUnavailableBanner } from "./LLMUnavailableBanner"
export { LinkExpiredOverlay } from "./LinkExpiredOverlay"
